### ISSUE TITLE
Mongo and rabbitmq in core?

### ISSUE THREAD

**Issue by brandonlamb** [jaguililla/hexagon#40]
More of a question, I was a little confused on why mongo and rabbitmq things would be in a core rest framework? Is that assuming too much? Seems like perhaps those should be abstracted behind something so that I dont have to pull in those dependencies since many people may not use either of those?

**Comment by jaguililla** [comment]
Thanks for your thoughts @brandonlamb. The project started as a library I'm using in other projects, and it is slowly evolving into something more modular.

Please take a look at the `develop` branch, as I'm splitting the project into modules there (still a WIP).

At the end of the year I will have a 1.0 version with support for *configuration*, *template processing*, *events (MQ)*, *storage* *http client* and *http server* with pluggable implementations.

Later on the roadmap is add support for other micro services requirements as *registry/discovery*, *metrics* and *logging*.

If you have any suggestion or comment, please reach me by filing an issue, or at https://kotlinlang.slack.com (Juanjo Aguililla).

Thanks again for taking the time to look at the code :)

**Comment by brandonlamb** [comment]
Definitely looks interesting!
